### ISSUE TITLE
First Release

### ISSUE THREAD

**Issue by nanomad** [SAIC-iSmart-API/saic-python-client-ng#1]
The current version, as it stands, is ready for its first release.

**Comment by tosate** [comment]
Hi @nanomad 

I have seen that you have opened a pull request in the MQTT gateway. You have mentioned that it's blocked by this issue.
Do you want me to merge the pull request or is there something I need to wait for?

How do we proceed?

**Comment by nanomad** [comment]
The MQTT gateway requires a first release of this library. I did run some tests with another user and the current version is working fine. It has feature parity with the old library, bugs included.

It needs to be released on pypi so that it can be pulled in as a dependency. I've never done  that, so I'll leave that to you :)

**Comment by tosate** [comment]
Okay, I have a busy day ahead of me. I'll try to take care of it on Tuesday or Wednesday.

**Comment by nanomad** [comment]
No worries, I'll test the gateway in the next couple of weeks. The old one works just fine so we are in no rush

**Comment by tosate** [comment]
Hi @nanomad,

I see that you have the python-publish.yml that specifies the GitHub workflow and you have pyproject.toml project file.
If we want to publish the NG client und my pypi account, we would have to put my API key as a secret in the project settings. I cannot do that and I cannot create a release of the library.

**Comment by nanomad** [comment]
Uhm I don't have admin rights either, I guess it's not under the python group so the admin rights go straight to @tisoft ?

**Comment by tosate** [comment]
I have tried to add the repoisory to the Python team:
`You do not have sufficient permissions to add the saic-python-client-ng repository to this team`

@tisoft can you have a look, please?

**Comment by tisoft** [comment]
I think I have added it to the python team. Please try again.

**Comment by tosate** [comment]
The repository belongs to the Python team now. Thank you @tisoft 
I have the maintainer role. However, I don't have the permission to define secrets for actions. Only administrators can do that.

**Comment by tisoft** [comment]
@tosate You should have admin permissions now

**Comment by tosate** [comment]
Thank you very much @tisoft 

Release 0.0.1 has been published on [PyPi](https://pypi.org/project/saic-ismart-client-ng/)
